service: fullThrottle

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-offline
custom:
  wsgi:
    app: app.app
  customStage: ${opt:stage, self:provider.stage}
  customEnvironment:
    HASURA_GRAPHQL_ENDPOINT:
      prod: https://full-throttle-sutirth.herokuapp.com/v1/graphql
    HASURA_ADMIN_SECRET:
      prod: *****

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'prod'}
  apiGateway:
    shouldStartNameWithService: true
  

  environment:
    HASURA_GRAPHQL_ENDPOINT: ${self:custom.customEnvironment.HASURA_GRAPHQL_ENDPOINT.${self:custom.customStage}}
    HASURA_ADMIN_SECRET: ${self:custom.customEnvironment.HASURA_ADMIN_SECRET.${self:custom.customStage}}


functions:
  app:
    handler: wsgi_handler.handler
    timeout: 30
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
